DROP TABLE IF EXISTS TD_demo1;
CREATE TABLE TD_demo1(
id INT AUTO_INCREMENT,
CONSTRAINT PK_id_TD_demo1 PRIMARY KEY (id)
);

INSERT INTO TD_demo1 VALUES (NULL);
INSERT INTO TD_demo1 VALUES (NULL);
SELECT LAST_INSERT_ID();

SELECT * FROM TD_demo1;
SHOW CREATE TABLE TD_demo1;

DELETE FROM TD_demo1;

INSERT INTO TD_demo1 VALUES (NULL);
INSERT INTO TD_demo1 VALUES (NULL);
SELECT LAST_INSERT_ID();

SELECT * FROM TD_demo1;
SHOW CREATE TABLE TD_demo1;

TRUNCATE TABLE  TD_demo1;

INSERT INTO TD_demo1 VALUES (NULL);
SELECT LAST_INSERT_ID();

SELECT * FROM TD_demo1;
SHOW CREATE TABLE TD_demo1;
DROP TABLE IF EXISTS TD_demo1;